trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: Veracode

stages:
- stage: SCA
  displayName: SCA
  dependsOn:
  jobs:
  - job: AgentBased
    steps: 
    - task: CmdLine@2
      inputs:
        script: |
          export SRCCLR_SCM_NAME=$(veracodeAppProfile)
          export SRCCLR_SCM_TYPE="GITHUB"
          export SRCCLR_SCM_TOKEN="$(tokenGitHub)"
          git config --global user.email "$(emailGit)"
          git config --global user.name "$(nomeGit)"
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s – scan --update-advisor --pull-request --allow-dirty
      displayName: 'Veracode SCA'
      continueOnError: true
